print("How old are you?",end='')
age=input()
print("How tall are you ? ", end=' ')
height=input()
print("How much do yo waigh?", end = ' ' )
weight = input()
print(f"So you're {age} old .{weight} tall and {weight} heavy")